#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/ ~/code ~/code/cpp ~/code/python ~/repos -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected

    if [[ -d "$selected/build" ]]; then
        tmux new-window -c "$selected/build" -n "Build"
    else
        tmux new-window -c "$selected"
    fi

	if [[ -d "$selected/.venv" ]]; then
		tmux send-keys -t $selected_name:0 "source $selected/.venv/bin/activate" C-m
		tmux send-keys -t $selected_name:1 "source $selected/.venv/bin/activate" C-m
	fi

	tmux select-window -t 0

    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected

    if [[ -d "$selected/build" ]]; then
        tmux new-window -c "$selected/build" -n "Build"
    else
        tmux new-window -c "$selected"
    fi

	if [[ -d "$selected/.venv" ]]; then
		tmux send-keys -t $selected_name:0 "source $selected/.venv/bin/activate" C-m
		tmux send-keys -t $selected_name:1 "source $selected/.venv/bin/activate" C-m
	fi

	tmux select-window -t 0
fi

tmux attach-session -t=$selected_name
